config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root 'events#index'
  
  resources :events
  resources :users
  resources :charges
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord

	belongs_to :user
	belongs_to :event

  after_create :new_attendance_email
  
	def new_attendance_email
    UserMailer.new_attendance_email(self).deliver_now
  end
end

app/models/event.rb
class Event < ApplicationRecord
	#validation de start_date
	validates :start_date, presence: true, if: :validate_start_date

     #validation de duration
	validates :duration, presence: true, if: :validate_duration

    #validation de title   
  validates :title, presence: true, length: { in: 5..140}

    #validation de description 
  validates :description, presence: true, length: {in: 20..1000}

    #validation de price 
  validates :price, presence: true, numericality: {only_integer: true}, inclusion: {in: 1..1000}

    #validation de location
  validates :location, presence: true

  
  has_many :attendances
  has_many :users ,through: :attendance 
  has_many :users
  belongs_to :admin, class_name: "User"


  def validate_start_date
  	errors.date(:start_date, "can't be in the past") if
  	!start_date.blank? and start_date < Date.today
  end

  def validate_duration
     duration%5 == 0  	
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	has_many :attendances
  has_many :events ,through: :attendance 
  has_many :events
	
	after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
 
  def name
  	return "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

def new
end

def create
  # Amount in cents
  @amount = 500

  customer = Stripe::Customer.create({
    email: params[:stripeEmail],
    source: params[:stripeToken],
  })

  charge = Stripe::Charge.create({
    customer: customer.id,
    amount: @amount,
    description: 'Rails Stripe customer',
    currency: 'usd',
  })

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def show
    @event=Event.find(params[:id].to_i)
  end

  def update
  end

  def edit
  end

  def index
    @event = Event.all
  end

  def new
    @event =Event.new
  end
  def create

    if user_signed_in?
    
   event_params = params.require(:event).permit(:start_date,:title,:duration,:location,:price,:description,:admin_id)
   @event = Event.new(event_params)
   @event.admin_id = current_user.id
   @event.save
   redirect_to events_path

    else
  redirect_to new_user_session_path
  end
  

  end
  def method_name
    

  @event=Event.new(
      admin_id: params[:admin_id].to_i,
      start_date: params[:start_date],
      title: params[:title],
      duration: params[:duration].to_i,
      location: params[:location],
      price: params[:price].to_i,
      description: params[:description]
      
      )
    if user_signed_in?
       

      @event.save
      puts "#"*60
      puts params.inspect 
      puts  @event.save
      puts "#"*60
    
      redirect_to events_path

    else
      redirect_to new_user_session_path
    end
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user= User.find(params[:id])
  	@event= Event.all
  end

  def edit
  	@user= User.new

  end

  def update
  	@user.save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/create.html.erb
<!-- page qui montre aux utilisateurs un message de réussite
-->

<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<!--page de paiement
-->
 <%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/index.html.erb
<div class="jumbotron" style="background-image: url(https://www.fgsmartevent.com/clients/smart-event/images/bandeau/grande_image/bandeau_titre_7_evenement_grand_public_couleur.jpg); background-repeat: no-repeat; background-size: cover;" >
<div class="container">
    <h1 class="display-3" style="color: white;">Bienvenue sur le site evènementiel!</h1>
    <p style="color: white;">Soyez prêt pour le prochain évènement!</p>
  </div>
</div>
</div>

<table class="table">
 <thead class="thead-dark">
   <tr><center>
     <th scope="col" class="text-primary">Numero</th>
     <th scope="col" class="text-danger">Titre</th>
     <th scope="col" class="text-danger">Description</th>
     <th scope="col" class="text-danger">Price</th>
     <th scope="col" class="text-danger">Localisation</th>    
   </center>    </tr>
 </thead>
 <tbody>
     <%@event.length.times do |i|%>
   <tr>
     <td scope="row"><%=@event[i].id%></td>
     <td><%=@event[i].title%>
     	 <a class="badge badge-warning"  href="/events/<%= @event[i].id%>">en savoir plus
     	 </a>       
     </td>
     <td><%=@event[i].description%></td>
     <td class="text-danger"><%=@event[i].price%> €</td>
     <td><%=@event[i].location%></td>
   </tr>
   <%end%>
 </tbody>
</table>

app/views/events/new.html.erb
<div class="container">
	 <%=simple_form_for @event do |f|%>
     <div class="form-group">
   <%= f.input :admin_id, :as => :hidden, :input_html => { :value => "#{current_user.id}" } %>
   </div>
  <div class="form-group">
  	 <%= f.input :start_date, placeholder: "Start date", class:"form-control", id: "inputStart"%>
  	</div>
  	
  <div class="form-row">
    <div class="form-group col-md-6">     
      <label for="inputTitle">Titre:</label>
      <%= f.text_field :title, placeholder: "Ecrivez votre titre", class:"form-control", id: "inputTitle"%>
    </div>
    <div class="form-group col-md-6">
      <label for="inputDuration">Durée:</label>
      <%= f.text_field :duration, placeholder: "Durée en minutes et multiple de 5", class:"form-control", id: "inputDuration"%>   
    </div>
  </div>
 <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputPrice">Prix:</label>
      <%= f.text_field :price, placeholder: "Prix en euro", class:"form-control", id: "inputPrice"%>      
    </div>
    <div class="form-group col-md-6">
      <label for="inputLocation">Lieu:</label>
      <%= f.text_field :location, placeholder: "Adresse précise", class:"form-control", id: "inputLocation"%>  
      
    </div>
  </div>
  <div class="form-group">
    <label for="inputDescription">Description:</label>
     <%= f.text_area :description, placeholder: "Description de l'évenement...", class:"form-control", id: "inputDescription"%> 
  </div>
  <div class="form-group">
 <%= f.submit 'Créer' ,class:"btn btn-outline-danger"%>
  </div>

  <%end%>

</div>

<% if @event.errors.any? %>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>Oups punaise!</strong> You should check in on some of those fields below.
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <p>Nous n'avons pas réussi à créer l'evenement pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    <% end %>


    <% if @event.errors.any? %>
      <div class="alert alert-danger" role="alert">
           A simple danger alert—check it out!
     </div>            <p>Nous n'avons pas réussi à créer l'evenement pour la (ou les) raison(s) suivante(s) :</p>
           <ul>
             <% @event.errors.full_messages.each do |message| %>
             <li><%= message %></li>
             <% end %>
           </ul>
     <% end %>

app/views/events/show.html.erb
<div class="card container" style="width: 30rem;">
  <img class="card-img-top" src="https://cdn.pixabay.com/photo/2017/11/08/14/42/event-2930674_960_720.png"  alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title"><strong><%=@event.title%></strong></h5>
    <p class="card-text"><%=@event.description%></p>
  </div>
  <ul class="list-group list-group-flush">

    <li class="list-group-item"><strong>Créer par:</strong><%=@event.admin.email%></li>
    <li class="list-group-item"><strong>Lieu:</strong><%=@event.location%></li>
    <li class="list-group-item"><strong>Date de debut: </strong><%=@event.start_date%></li>
    <li class="list-group-item"><strong>Date de fin: </strong><%="#{@event.start_date + (@event.duration * 60)}"%></li>
    <li class="list-group-item"><strong>Prix: </strong><%=@event.price%></li>
    <li class="list-group-item"><strong>Durée:</strong><%=@event.duration%> minutes</li>

    
  </ul>
  <div class="card-body">
    <span class="card-link"><%= link_to "Back", :back %><span>
    
    <a href="#" class="card-link">Another link</a>
  </div>
</div>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Events Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>
  <body>


<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= events_path%>">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-success" href="<%= new_event_path%>">Create Event</a>
      </li>
<!--
====================================================================================================

----------------------------lien pour user non connecter-----------

====================================================================================================
--> 
<% if user_signed_in?%>

 <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Profil
        </a>   
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/users/<%= current_user.id%>">Mon profil</a>
                  
          <spam class="dropdown-item" ><%= link_to "Se deconnecter", destroy_user_session_path, :method => :delete %></spam>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="<%=edit_user_registration_path%>">Modifier profil</a>
        </div>
      </li>     
    </ul>

      
<!--
====================================================================================================

----------------------------lien pour user non connecter------------------------------

====================================================================================================
-->   
<% else %>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Connection
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="<%= new_user_registration_path%>">S'inscrire</a>
          <a class="dropdown-item" href="<%= new_user_session_path%>">Se connecter</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
     

<%end%>


  </div>
</nav>




    <%= yield %>
  </body>
</html>

app/views/layouts/charges.html.erb
 <!DOCTYPE html> 
 <html> 
	 <head>
	 	
	 </head> 
 <body> 




 	<%= yield %> 
 </body> 
 </html> 

app/views/users/edit.html.erb
    <div class="form-group container">
      <label for="inputFirst_name">First_name:</label>
      <input type="text" class="form-control" id="inputFirst_name" placeholder="First_name">
    </div>
    <div class="form-group container">
      <label for="inputLast_name">Last_name</label>
      <input type="text" class="form-control" id="inputLast_name" placeholder="Last_name">
    </div>


<div class="form-group container">
    <label for="exampleDescription">Description</label>
    <textarea class="form-control" id="exampleDescription" placeholder="Decrivez votre personnalité"rows="3"></textarea>
    <button type="submit" class="btn btn-primary">Confirm identity</button>
</div>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Profil</title>
</head>
<body>
<div>
    <p>
      <strong>Email:</strong>
      <%= @user.email %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @user.descritpion %>
    </p>

    <p>
      <strong>First name:</strong>
      <%= @user.first_name %>
    </p>

    <p>
      <strong>Last name:</strong>
      <%= @user.last_name %>
    </p>
</div>
  <span class="badge badge-pill badge-dark"><%= link_to 'Modifier profil', edit_user_path(@user) %>  </span>
<div>
    <h3> liste de vos événement </h3>
    <p>
        Titre :
        <%@event.each do |i|%>
            <%if i.admin.id == @user.id%>
                <%=i.title%></br><a class="badge badge-warning"  href="/events/<%= i.id%>">en savoir plus
       </a> 
            <%end%>
        <%end%>
</div>
</body>
</html>